package com.kaelith.aureon.features.secrets.utils.routes

import com.kaelith.aureon.AureonCore
import com.kaelith.aureon.annotations.Module
import com.kaelith.aureon.features.secrets.SecretRoutes
import com.google.gson.GsonBuilder
import com.google.gson.JsonObject
import net.minecraft.core.BlockPos
import java.awt.Color
import java.io.File

@Module
object RouteRegistry {
    private val ROUTES_FILE get() = File("${AureonCore.PATH}/routes/${SecretRoutes.routeFile}")
    private val gson = GsonBuilder().disableHtmlEscaping().create()
    private var routeFile: RouteFile = RouteFile()

    init {
        load()
    }

    fun load() {
        if (!ROUTES_FILE.exists()) {
            AureonCore.LOGGER.info("RouteRegistry: ${SecretRoutes.routeFile} not found, creating new file")
            save()
            return
        }

        runCatching {
            val json = ROUTES_FILE.readText()
            val obj = gson.fromJson(json, JsonObject::class.java)

            val name = obj["#name"]?.asString ?: "Default secret routes"
            val origin = obj["#origin"]?.asString ?: "generated by Aureon"
            val version = obj["Version"]?.asString ?: "1.0"

            val routes = mutableMapOf<String, RouteData>()

            for ((key, value) in obj.entrySet()) {
                if (key.startsWith("#")) continue
                if (key == "Version") continue

                // Parse steps array
                val stepsJson = value.asJsonArray
                val steps = stepsJson.map { stepElement ->
                    gson.fromJson(stepElement, StepDataSerializable::class.java)
                }

                routes[key] = RouteData(steps)
            }

            routeFile = RouteFile(name, origin, version, routes)

            AureonCore.LOGGER.info("RouteRegistry: Successfully loaded ${routes.size} rooms")
        }.onFailure {
            AureonCore.LOGGER.error("RouteRegistry: Failed to load ${SecretRoutes.routeFile} — ${it.message}")
        }
    }

    fun save() {
        runCatching {
            val sb = StringBuilder()

            sb.append("{\n")

            sb.append("    \"#name\": \"${routeFile.`#name`}\",\n")
            sb.append("    \"#origin\": \"${routeFile.`#origin`}\",\n")
            sb.append("    \"Version\": \"${routeFile.Version}\"")

            val entries = routeFile.routes.entries.toList()

            if (entries.isNotEmpty()) {
                sb.append(",\n\n") // only add comma + blank line if routes exist

                entries.forEachIndexed { index, (room, data) ->
                    sb.append("    \"").append(room).append("\":")
                    sb.append(gson.toJson(data.steps))

                    if (index != entries.lastIndex) sb.append(",")
                    sb.append("\n")
                }
            } else {
                sb.append("\n")
            }

            sb.append("}")

            ROUTES_FILE.parentFile.mkdirs()
            ROUTES_FILE.writeText(sb.toString())

            AureonCore.LOGGER.info("RouteRegistry: Saved ${SecretRoutes.routeFile}")
        }.onFailure {
            AureonCore.LOGGER.error("RouteRegistry: Failed to save ${SecretRoutes.routeFile} — ${it.message}")
        }
    }

    fun reload() {
        AureonCore.LOGGER.info("RouteRegistry: Reloading ${SecretRoutes.routeFile}...")

        runCatching {
            load()
            AureonCore.LOGGER.info("RouteRegistry: Reload complete")
        }.onFailure {
            AureonCore.LOGGER.error("RouteRegistry: Reload failed — ${it.message}")
        }
    }

    fun saveRoute(roomName: String, steps: List<StepData>) {
        val serializable = RouteData(steps.map { it.toSerializable() })
        routeFile.routes[roomName] = serializable
        save()
    }

    fun getRoute(roomName: String): List<StepData>? =
        routeFile.routes[roomName]?.toRuntime()

    fun getAll(): Map<String, RouteData> =
        routeFile.routes

    data class RouteFile(
        val `#name`: String = "Default secret routes",
        val `#origin`: String = "generated by Aureon",
        val Version: String = "1.0",
        val routes: MutableMap<String, RouteData> = mutableMapOf()
    )

    data class RouteData(
        val steps: List<StepDataSerializable>
    ) {
        fun toRuntime(): List<StepData> =
            steps.map { it.toRuntime() }
    }

    data class StepDataSerializable(
        val waypoints: List<WaypointDataSerializable>,
        val line: List<List<Int>> // [[x, y, z], ...]
    )

    data class WaypointDataSerializable(
        val pos: List<Int>,       // [x, y, z]
        val type: String,
        val name: String?,
        val color: List<Int>?     // [r, g, b]
    )

    fun BlockPos.toList() = listOf(x, y, z)
    fun Color.toList() = listOf(red, green, blue)

    fun StepData.toSerializable() = StepDataSerializable(
        waypoints = waypoints.map { it.toSerializable() },
        line = line.map { it.toList() }
    )

    fun WaypointData.toSerializable() = WaypointDataSerializable(
        pos = pos.toList(),
        type = type.name,
        name = name,
        color = color?.toList()
    )

    fun StepDataSerializable.toRuntime(): StepData {
        val runtimeWaypoints = waypoints.map { it.toRuntime() }.toMutableList()
        val runtimeLine = line.map { BlockPos(it[0], it[1], it[2]) }.toMutableList()
        return StepData(runtimeWaypoints, runtimeLine)
    }

    fun WaypointDataSerializable.toRuntime(): WaypointData {
        val pos = BlockPos(this.pos[0], this.pos[1], this.pos[2])
        val type = WaypointType.valueOf(this.type)
        val colorObj = this.color?.let { Color(it[0], it[1], it[2]) }
        return WaypointData(pos, type, name, colorObj)
    }
}
